fixtures:
  repositories:
    awscli: "https://github.com/asgoodasnu/puppet-awscli.git"
      # from awscli
    'concat':
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.2"
    'stdlib':
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '4.4.0'
  symlinks:
    ec2cronjob: "#{source_dir}"
